### ISSUE TITLE
make: *** No rule to make target 'install'.  Stop.

### ISSUE THREAD

**Issue by ZiweiSong96** [SJTU-IPADS/disb#1]
HI
When I build and install DISB tools. It says No rule to make target. How can I install DISB tools?

"make: *** No rule to make target 'install'.  Stop."
![1660909051557](https://user-images.githubusercontent.com/33652840/185610218-274ec379-0307-4b5e-896f-c3311065fc20.png)

**Comment by Naplesoul** [comment]
Thank for your feedback! We have fixed this issue in release v1.0.
