### ISSUE TITLE
Question about the REAL.json trace

### ISSUE THREAD

**Issue by fotstrt** [SJTU-IPADS/disb#2]
Hello!
Thank you for open-sourcing the benchmark suite!

I was reading your [paper](https://www.usenix.org/system/files/osdi22-han.pdf), and I was wondering whether the [REAL.json](https://github.com/SJTU-IPADS/disb/blob/main/benchmarks/workloads/REAL.json) trace corresponds to the Real-world workload from Apollo used in your experiments.

Thank you!

**Comment by francis0407** [comment]
Yes, the loads with the label `"type": "trace"` are from the real-world workload.

**Comment by fotstrt** [comment]
Great, thank you very much! We are thinking to concatenate all of the five traces and build a large one. Do you think that would make sense based on the real-world applications of autonomous driving?

**Comment by francis0407** [comment]
These five timestamp lists are the submit times of inference requests from Apollo's five different algorithm modules (or clients) in one run.

You can use each of these five lists as five different workloads, or as a large load with five concurrent clients (this is how DISB uses them, and I think that's also what you mean by `concatenate all of the five traces and build a large one`).

**Comment by fotstrt** [comment]
I see, thank you!
