### ISSUE TITLE
Question about rps of Apollo real time trace

### ISSUE THREAD

**Issue by atomicapple0** [SJTU-IPADS/disb#5]
In the Reef OSDI'22 paper, it states:
> Due to the low load of real-time tasks in the realworld trace (about 43 reqs/s)...

I assume this trace is referring to the [REAL.json](https://github.com/SJTU-IPADS/disb/blob/main/benchmarks/workloads/REAL.json) file. From parsing this script, I see the following summary statistics:
```
duration: 60s
[vgg19] count:1020, rps:17.0
[densenet201] count:1260, rps:21.0
[resnet152] count:1260, rps:21.0
[inceptionv3] count:1560, rps:26.0
[distilbert] count:1140, rps:19.0
Total RPS: 104.0
```

It seems that the Apollo trace in this repo issues around 104 rps but the paper claims 43 rps. Is there a different version of the trace which matches what was ran in the paper?

**Comment by Naplesoul** [comment]
Thank you for your feedback! It seems that we have uploaded the wrong json file. We have updated [REAL.json](https://github.com/SJTU-IPADS/disb/blob/main/benchmarks/workloads/REAL.json) to be consistent with the paper in MR #6.
